//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using Point = RosMessageTypes.Geometry.PointMsg;

namespace RosMessageTypes.Spot
{
    public class FootState : Message
    {
        public const string RosMessageName = "spot_msgs/FootState";

        //  Contact
        public const byte CONTACT_UNKNOWN = 0;
        public const byte CONTACT_MADE = 1;
        public const byte CONTACT_LOST = 2;
        public Point foot_position_rt_body;
        public byte contact;

        public FootState()
        {
            this.foot_position_rt_body = new Point();
            this.contact = 0;
        }

        public FootState(Point foot_position_rt_body, byte contact)
        {
            this.foot_position_rt_body = foot_position_rt_body;
            this.contact = contact;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(foot_position_rt_body.SerializationStatements());
            listOfSerializations.Add(new[]{this.contact});

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.foot_position_rt_body.Deserialize(data, offset);
            this.contact = data[offset];;
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "FootState: " +
            "\nfoot_position_rt_body: " + foot_position_rt_body.ToString() +
            "\ncontact: " + contact.ToString();
        }
    }
}
