//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class FootStateArrayMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/FootStateArray";
        public override string RosMessageName => k_RosMessageName;

        public FootStateMsg[] states;

        public FootStateArrayMsg()
        {
            this.states = new FootStateMsg[0];
        }

        public FootStateArrayMsg(FootStateMsg[] states)
        {
            this.states = states;
        }

        public static FootStateArrayMsg Deserialize(MessageDeserializer deserializer) => new FootStateArrayMsg(deserializer);

        private FootStateArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.states, FootStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "FootStateArrayMsg: " +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
