//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    public class FootStateArray : Message
    {
        public const string RosMessageName = "spot_msgs/FootStateArray";

        public FootState[] states;

        public FootStateArray()
        {
            this.states = new FootState[0];
        }

        public FootStateArray(FootState[] states)
        {
            this.states = states;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(states.Length));
            foreach(var entry in states)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var statesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.states= new FootState[statesArrayLength];
            for(var i = 0; i < statesArrayLength; i++)
            {
                this.states[i] = new FootState();
                offset = this.states[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "FootStateArray: " +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }


    }
}
